### ISSUE TITLE
Incorrectly escaped private tag values cause BufferOverflowException in DicomOutputStream

### ISSUE THREAD

**Issue by homerocda** [dcm4che/dcm4che#818] opened 2020-11-10 15:35 UTC
When the attributes specify ISO 2022 IR 87 and ISO 2022 IR 13 as the default character sets, in this order, and the private tag data is written in ASCII or UTF8 *without* starting with the escape sequence, a BufferOverflowException is thrown while writing to a file after it has been read from an input stream using ImplicitVRLittleEndian or ExplicitVRBigEndianRetired.

This does not happen if standard dicom attribute values in ASCII or UTF8 miss an escape sequence at the beginning.

```
public void test() {
    // Original attributes
    Attributes attributes = new Attributes();
    attributes.setSpecificCharacterSet("ISO 2022 IR 87", "ISO 2022 IR 13");
    attributes.setBytes(Tag.PatientName, VR.PN, "DOE^JOHN^^".getBytes(StandardCharsets.US_ASCII));
    attributes.setBytes(0x330010, VR.LO, "Private Tag Group 1".getBytes(StandardCharsets.US_ASCII));
    attributes.setBytes(0x331001, VR.LO, "AA".getBytes(StandardCharsets.US_ASCII));

    // Write attibutes using Implicit VR
    ByteArrayOutputStream byteOs = new ByteArrayOutputStream();
    DicomOutputStream dicomOutputStream = new DicomOutputStream(byteOs, UID.ImplicitVRLittleEndian);
    Attributes newAttrs = new Attributes();
    newAttrs.addAll(attributes);
    dicomOutputStream.writeDataset(null, newAttrs);
    dicomOutputStream.close();

    // Read attributes using Implicit VR
    ByteArrayInputStream byteIs = new ByteArrayInputStream(byteOs.toByteArray());
    DicomInputStream dicomInputStream = new DicomInputStream(byteIs, UID.ImplicitVRLittleEndian);
    Attributes attributesAfterNetwork = dicomInputStream.readDataset(-1, -1);

    // Save data into a file -- Throws exception
    File file = File.createTempFile("temp", "dcm");
    DicomOutputStream fileDicomOs = new DicomOutputStream(file);
    fileDicomOs.writeDataset(null, attributesAfterNetwork);
    fileDicomOs.close();
}

```

**Comment by hczedik** [comment] 2020-11-10 15:42
Related to https://github.com/dcm4che/dcm4che/issues/325

@gunterze, it seems you did not fix this BufferOverflowException in all cases of incorrectly encoded data.

**Comment by gunterze** [comment] 2020-11-24 09:40
The failure is caused by specifying a Character Set in value 1 of _(0008,0005) Specific Character Set_ which does not include the default character set, which is not permitted according [PS 3.5, 6.1.2.3 Encoding of Character Repertoires](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_6.1.2.3):
> The replacement character repertoire shall be specified in value 1 of the Attribute Specific Character Set (0008,0005).

**Comment by gunterze** [comment] 2020-11-24 10:14
Fixed by reordering / extending specified  Character Sets to ensure that the first Character Set includes the default character set, and write INFO log, if the specified Character Sets had to be adjusted, e.g.:
```
INFO  - Invalid Specific Character Set: [ISO 2022 IR 87\ISO 2022 IR 13] - treat as [ISO 2022 IR 13\ISO 2022 IR 87]
```

**Closed** 2020-11-24 10:16 UTC

**Comment by hczedik** [comment] 2020-11-24 10:17
Thanks a lot, Gunter!
