### ISSUE TITLE
LIB-441  Reading first frame in large multiframe is very slow

### ISSUE THREAD

**Issue by hczedik** [dcm4che/dcm4che#51] opened 2017-04-03 13:12 UTC
This issue was migrated from Jira.

Please check the original Jira issue for additional information and the actual Reporter:
http://dcm4che.org/jira/browse/LIB-441

**Comment by er453r** [comment] 2018-07-11 13:36
@hczedik This is a duplicate of #48, look there for a solution.

**Closed** 2018-07-11 14:47 UTC
Labels: improvement
