### ISSUE TITLE
Decompress JPEG 2000 images with  YCC 422 or YCC 420 sub-sampling on the 3 channels fails with: "OpenJPEG2000: tiles are not supported"

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#1405] opened 2024-03-04 11:31 UTC
```
$ dcm2jpg /tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.dcm /tmp/frame1.jpg
Native OpenCV library has been found in /home/gunter/dcm4che/lib/linux-x86-64/libopencv_java.so
11:50:14.256 DEBUG - Decompressor: org.dcm4che3.opencv.NativeImageReader
11:50:14.258 DEBUG - Start decompressing frame #1
Mar 04, 2024 11:50:14 AM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
imread_('memory image'): can't read data: OpenCV(4.8.1) /work/modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp:689: error: (-2:Unspecified error) in function 'virtual bool cv::detail::Jpeg2KOpjDecoderBase::readData(cv::Mat&)'
> OpenJPEG2000: tiles are not supported (expected: '(int)comp.dx == 1'), where
>     '(int)comp.dx' is 2
> must be equal to
>     '1' is 1

Failed to convert /tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.dcm: w and h must be > 0
java.lang.IllegalArgumentException: w and h must be > 0
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:281)
	at org.weasis.opencv.op.ImageConversion.toBufferedImage(ImageConversion.java:84)
	at org.weasis.opencv.op.ImageConversion.toBufferedImage(ImageConversion.java:120)
	at org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:252)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:458)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.readImageFromDicomInputStream(Dcm2Jpg.java:438)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.convert(Dcm2Jpg.java:425)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.mconvert(Dcm2Jpg.java:412)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.main(Dcm2Jpg.java:381)
```
[TCGA-AF-2687-01Z-00-DX1_im_0-1.dcm.gz](https://github.com/dcm4che/dcm4che/files/14480551/TCGA-AF-2687-01Z-00-DX1_im_0-1.dcm.gz)

TCGA-AF-2687-01Z-00-DX1_im_0-1.dcm encapsulates the first frame of VL Whole Slide Microscopy Image: `IDC/TCGA-AF-2687/images/TCGA-AF-2687-01Z-00-DX1_im_0.dcm` in [test data](https://www.dropbox.com/scl/fo/wn6qfm8rc5eyojj6rfj27/h?rlkey=r8pb5bwj95xia1120mf5vr263&dl=0) for upcoming WG26 Annotation Connectathon.

Considering
```
1248: (0008,1090) LO #52 [Aperio converted by com.pixelmed.convert.TIFFToDicom] ManufacturerModelName
```
and
```
1844: (0018,A001) SQ #-1 ContributingEquipmentSequence
1856: >(FFFE,E000) #-1 Item #1
1864: >(0008,0070) LO #8 [PixelMed] Manufacturer
1880: >(0008,0080) LO #8 [PixelMed] InstitutionName
1896: >(0008,0081) ST #10 [Bangor, PA] InstitutionAddress
1914: >(0008,1040) LO #20 [Software Development] InstitutionalDepartmentName
1942: >(0008,1090) LO #32 [com.pixelmed.convert.TIFFToDicom] ManufacturerModelName
1982: >(0018,1020) LO #34 [Vers. Sat May 28 11:42:06 EDT 2022] SoftwareVersions
2024: >(0018,A002) DT #24 [20220612165335.074+0000] ContributionDateTime
2056: >(0018,A003) ST #24 [TIFF to DICOM conversion] ContributionDescription
```
of the VL Whole Slide Microscopy Image, the JPEG2000 object may have been generated by https://github.com/ImagingDataCommons/idc-wsi-conversion

**Comment by gunterze** [comment] 2024-03-04 17:15
Verified, that the failure occurs also with plain OpenCV 4.5.4:

```
$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> print(cv2.__version__)
4.5.4
>>> import sys
>>> img = cv2.imread("/tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.j2k")
[ WARN:0] global ./modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp (607) readData OpenJPEG2000: Image has unknown or unspecified color space, SRGB is assumed
imread_('/tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.j2k'): can't read data: OpenCV(4.5.4) ./modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp:641: error: (-2:Unspecified error) in function 'virtual bool cv::detail::Jpeg2KOpjDecoderBase::readData(cv::Mat&)'
> OpenJPEG2000: tiles are not supported (expected: '(int)comp.dx == 1'), where
>     '(int)comp.dx' is 2
> must be equal to
>     '1' is 1
```

but not with plain OpenJPEG v2.4.0:
```console
$ opj_decompress -i /tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.j2k -o /tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.png

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile /tmp/TCGA-AF-2687-01Z-00-DX1_im_0-1.png
decode time: 2 ms
```

**Comment by nroduit** [comment] 2024-03-04 21:31
Yes, this is normal, because in OpenCV only the openjp2 module is included and image decompression with tiles is not supported by default, see[ the code](https://github.com/opencv/opencv/blob/4.x/modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp#L641-L646).

Tile decompression should be implemented for all structure types in a way similar to opj_decompress. This implementation will not be suitable for huge tiled images.

For WSI images, this is the first time I've seen tiles in a single frame. We have Leica scanners that produce DICOM natively and they produce multiframes representing tiles but where there is no more than one tile in a frame.

**Comment by dclunie** [comment] 2024-03-05 16:08
@nroduit the issue still needs to be resolved in dcm4che - these are valid DICOM and J2K, AFAIK, and they are encountered in practice, so failure to support them means the need to use a different toolkit/archive than dcm4che until the issue is resolved.

**Comment by gunterze** [comment] 2024-03-06 13:56
Opened https://github.com/opencv/opencv/issues/25170

**Comment by nroduit** [comment] 2024-03-11 08:45
The problem is linked to YCC 422 or YCC 420 sub-sampling on the 3 channels and not to tiling as the error message suggests.

I've managed to make some changes to display correctly those images that have sub-sampling 422. However, I still need to run a few tests to make sure there are no side effects.

**Comment by gunterze** [comment] 2024-03-15 15:48
Verified that the J2KI sample datasets from WG4 (ftp://medical.nema.org/MEDICAL/Dicom/DataSets/WG04/compsamples_j2k.tar ) do not use sub-sampling. E.g.:
```console
dd if=IMAGES/J2KI/US1_J2KI of=US1_J2KI.j2k bs=1 skip=1542 count=57590
57590+0 records in
57590+0 records out
57590 bytes (58 kB, 56 KiB) copied, 0,0730085 s, 789 kB/s
```
```console
opj_dump -i US1_J2KI.j2k

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
Image info {
	 x0=0, y0=0
	 x1=640, y1=480
	 numcomps=3
		 component 0 {
		 dx=1, dy=1
		 prec=8
		 sgnd=0
	}
		 component 1 {
		 dx=1, dy=1
		 prec=8
		 sgnd=0
	}
		 component 2 {
		 dx=1, dy=1
		 prec=8
		 sgnd=0
	}
}
...
```
so the error did not show up on decompression of that images.

Whereas the WG26 Annotation Connectathon test images do, e.g.
```console
dd if=IDC/TCGA-AF-2689/images/TCGA-AF-2689-01Z-00-DX1_im_3.dcm of=TCGA-AF-2689-01Z-00-DX1_im_3_1.j2k bs=1 skip=153466 count=366
366+0 records in
366+0 records out
366 bytes copied, 0,00264185 s, 139 kB/s
```
```console
opj_dump -i TCGA-AF-2689-01Z-00-DX1_im_3_1.j2k

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
Image info {
	 x0=0, y0=0
	 x1=256, y1=256
	 numcomps=3
		 component 0 {
		 dx=1, dy=1
		 prec=8
		 sgnd=0
	}
		 component 1 {
		 dx=2, dy=1
		 prec=8
		 sgnd=0
	}
		 component 2 {
		 dx=2, dy=1
		 prec=8
		 sgnd=0
	}
}
...
```

**Comment by gunterze** [comment] 2024-03-21 12:45
Hi Nicolas,

Can you give us a rough estimate, if you think you will be able and if so how long it will take to extend the OpenCV integration of OpenJPEG, to also support decoding of J2KI images with downsampled channels?

Thanks,
Gunter

**Closed** 2024-03-27 14:35 UTC
Labels: bug
