### ISSUE TITLE
transcoding in JPEG2000 lossy doesn't set LossyImageCompressionRatio to the appropriate value

### ISSUE THREAD

**Issue by sylvain-rouquette** [dcm4che/dcm4che#1082] opened 2021-12-17 10:28 UTC
**Describe the bug**
LossyImageCompressionRatio should have a value of the ratio used to compress in JPEG2000 Lossy, but instead is always 10.

**To Reproduce**
1. run `dcm2dcm --j2ki -Q 100 input.dcm output.dcm`
2. open output.dcm and check LossyImageCompressionRatio 
3. LossyImageCompressionRatio  = 10

**Expected behavior**
LossyImageCompressionRatio  should be 100

**Desktop (please complete the following information):**
 - OS: Windows 10
 - dcm4che 5.25.0, binary download from sourceforge

**Comment by nroduit** [comment] 2021-12-20 07:36
Unfortunately, there is no way to automate the build without having Mac OS + hardware. I'm waiting for a solution from [Github](https://github.com/actions/virtual-environments/issues/2187) because for the moment I have neither hardware M1 nor the will to deal with this build manually.

However I guess it is possible to use a version of Java x86 with Rosetta.

**Comment by sylvain-rouquette** [comment] 2021-12-20 08:39
Hello,

I don't think the problem is related to windows. I downloaded the exe
because I have another problem, and I wanted to check if the command line
tool was working.

I reproduced the problem with LossyImageCompressionRatio in docker (debian)
and dcm4che 5.23.0.

The other problem I have is that I can't override the ratioFactor, but this
doesn't happen with the command line tool, this could be related to 5.23.0.
I will upgrade and test again.

But for the dicom tag, this should be reproducible on other OSes.

*Sylvain ROUQUETTE*
Software Architect
M : +33-6-61-70-53-91

<https://incepto-medical.com/>

Tour Montparnasse, 53ème étage
75015 Paris, France

<https://www.instagram.com/inceptomedical/>
<https://www.linkedin.com/company/inceptomedical>
<https://twitter.com/inceptomedical>
<https://www.facebook.com/inceptomedical/>
https://incepto-medical.com


Le lun. 20 déc. 2021 à 08:36, Nicolas Roduit ***@***.***> a
écrit :

**Comment by nroduit** [comment] 2021-12-20 09:13
Sorry for the previous message which was intended for another issue.

I propose a [fix for this issue](https://github.com/dcm4che/dcm4che/pull/1085).

**Comment by sylvain-rouquette** [comment] 2021-12-20 09:49
ok, seems good, thanks.
FYI, the other bug I mentioned above (compression not working) was related to version 5.23.0. It works with version 5.25.0.

**Comment by gunterze** [comment] 2021-12-27 13:50
Not reproducible:
```
$ dcm2dcm --j2ki MG1_UNC MG1_J2KI-10
Native OpenCV library has been found in /home/gunter/dcm4che/lib/linux-x86-64/libopencv_java.so
Dec 27, 2021 2:48:26 PM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
14:48:26.413 DEBUG - Compressor: org.dcm4che3.opencv.NativeJ2kImageWriter
14:48:28.995 DEBUG - Compressed frame #1 in 2523 ms, ratio 13.334107:1
MG1_UNC -> MG1_J2KI-10
```
```
$ dcm2dcm --j2ki -Q 100 MG1_UNC MG1_J2KI-100
Native OpenCV library has been found in /home/gunter/dcm4che/lib/linux-x86-64/libopencv_java.so
Dec 27, 2021 2:48:38 PM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
14:48:38.727 DEBUG - Compressor: org.dcm4che3.opencv.NativeJ2kImageWriter
14:48:41.238 DEBUG - Compressed frame #1 in 2452 ms, ratio 133.41888:1
MG1_UNC -> MG1_J2KI-100
```
```
$ ls -l MG1*
-rw-rw-r-- 1 gunter gunter  2144786 Dez 27 14:48 MG1_J2KI-10
-rw-rw-r-- 1 gunter gunter   215556 Dez 27 14:48 MG1_J2KI-100
-rw-r--r-- 1 gunter gunter 28582296 Aug 27  2004 MG1_UNC
```

**Closed by gunterze** 2021-12-27 13:50 UTC

**Comment by nroduit** [comment] 2021-12-27 19:03
The description of the bug may not be explicit enough but I confirm that the compression ratio works on image compression but not in the DICOM LossyImageCompressionRatio field.

The value put in LossyImageCompressionRatio is the one found in the properties file of the decoders. This is why the value is always **10**.

The [PR](https://github.com/dcm4che/dcm4che/pull/1085/) corrects this problem and retrieves the value in the decoder parameters by reflection because this class is not visible by this model.

Process with dcm4che 5.25.0:
![Sélection_032](https://user-images.githubusercontent.com/993975/147500001-a8a2a1e4-ec32-4d00-906f-2a06c6706220.png)

**Comment by gunterze** [comment] 2021-12-27 20:07
Ok, I see.
